language: java
os: osx
jdk:
  - openjdk11

# branches:
#   only:
#     - master\

#TRAVIS CI SERVER HOME
cache:
  directions:
    - $HOME/.m2

before_install:
  - chmod +x mvnw

script: "./mvnw clean install"

#NOTIFICATION
notifications:
  email:
    recipients:
      - newkayak12@gmail.com
